#' Unpublished map between B73 v3 and v4 gene model ids
#'
#' Map between B73 v3 and v4 gene model ids generated by Maggie using SynMap. This includes merged v3 models
#' but not split v3 models.  B73 V3 ids are of the form GRMZM and B73 v4 ids are of the form Zm.  V3 also
#' includes some "AC" ids.  These legacy ids were generated from BAC's.  The suffix on the AC ids, "FG###"
#' refers to the sequence the expressing segment appeared on that particular BAC.
#'
#' @docType data
#' @usage data(maize.genes.v3_to_v4.map)
#' @keywords datasets
#'
#' @format A data frame columns [v3_id, v4_id].
"maize.genes.v3_to_v4.map"

#' CornCyc 8 gene frameIDs mapped to B73 v4 gene models.
#'
#' This data is a direct dump from CornCyc 8.0.1.  It represents all genes in the database that have a
#' B73 v4 id associated with them.
#'
#' @docType data
#' @usage data(corncyc.gene.map)
#' @keywords datasets
#'
#' @format A data frame in long format.
"corncyc.gene.map"

#' CornCyc 8 reaction frameIDs mapped to gene frameIDs.
#'
#' This data is a direct dump from CornCyc 8.0.1.  It represents all reactions in the database that have a
#' gene frames associated with them.
#'
#' @docType data
#' @usage data(corncyc.reaction.gene.map)
#' @keywords datasets
#'
#' @format A data frame in long format.
"corncyc.reaction.gene.map"

#' CornCyc 8 pathway frameIDs mapped to reaction frameIDs.
#'
#' This data is a direct dump from CornCyc 8.0.1.  It represents all pathways in the database that have a
#' reaction frames associated with them, excluding superpathways.
#'
#' @docType data
#' @usage data(corncyc.pathway.reaction.map)
#' @keywords datasets
#'
#' @format A data frame in long format.
"corncyc.pathway.reaction.map"
