#' Unpublished map between B73 v3 and v4 gene model ids
#'
#' Map between B73 v3 and v4 gene model ids generated by Maggie using SynMap. This includes merged v3 models
#' and split v3 models.  B73 V3 ids are of the form GRMZM and B73 v4 ids are of the form Zm.  V3 also
#' includes some "AC" ids, but excludes some non-standard ids.  The "AC" legacy ids were generated from BAC's.
#' The suffix on the AC ids, "FG###" refers to the sequence the expressing segment appeared on that particular BAC.
#' This is the revised mapping (version 2) created Jan 2018.
#'
#' @docType data
#' @usage data(maize.genes.v3_to_v4.map)
#' @keywords datasets
#'
#' @format A data frame columns [v3_id, v4_id, type].
"maize.genes.v3_to_v4.map"

#' Classical gene models mapped to B73 v3 gene model ids
#'
#' Provided by MaizeGDB, mapping is 1 to 1.
#'
#' @docType data
#' @usage data(maize.genes.classical_to_v3.map)
#' @keywords datasets
#'
#' @format A data frame columns [classical, v3_id].
"maize.genes.classical_to_v3.map"

#' UniProt Accessions mapped to B73 v3 gene model ids
#'
#' Downloaded from UniProt.  Parses "Gramene" cross-reference field for the B73 ids.  Mapping is may include many-to-many
#' relationships, but has unnested the B73 ids where possible.
#'
#' @docType data
#' @usage data(maize.genes.uniprot_to_v3.map)
#' @keywords datasets
#'
#' @format A data frame columns [UniProt_Acc, v3_id].
"maize.genes.uniprot_to_v3.map"

#' UniProt Accessions mapped to B73 v4 gene model ids
#'
#' Downloaded from UniProt.  Parses "Gramene" cross-reference field for the B73 ids.  Mapping is may include many-to-many
#' relationships, but has unnested the B73 ids where possible.
#'
#' @docType data
#' @usage data(maize.genes.uniprot_to_v4.map)
#' @keywords datasets
#'
#' @format A data frame columns [UniProt_Acc, v4_id].
"maize.genes.uniprot_to_v4.map"

#' CornCyc 8 gene frameIDs mapped to B73 v4 gene models.
#'
#' This data is a direct dump from CornCyc 8.0.1.  It represents all genes in the database that have a
#' B73 v4 id associated with them.
#'
#' @docType data
#' @usage data(corncyc.gene.map)
#' @keywords datasets
#'
#' @format A data frame in long format.
"corncyc.gene.map"

#' CornCyc 8 reaction frameIDs mapped to gene frameIDs.
#'
#' This data is a direct dump from CornCyc 8.0.1.  It represents all reactions in the database that have a
#' gene frames associated with them.
#'
#' @docType data
#' @usage data(corncyc.reaction.gene.map)
#' @keywords datasets
#'
#' @format A data frame in long format.
"corncyc.reaction.gene.map"

#' CornCyc 8 pathway frameIDs mapped to reaction frameIDs.
#'
#' This data is a direct dump from CornCyc 8.0.1.  It represents all pathways in the database that have a
#' reaction frames associated with them, excluding superpathways.
#'
#' @docType data
#' @usage data(corncyc.pathway.reaction.map)
#' @keywords datasets
#'
#' @format A data frame in long format.
"corncyc.pathway.reaction.map"

#' Map from genes to all available transcripts.
#'
#' Parsed from the zea mays b73 v4.37 gff3 file available at ftp://ftp.ensemblgenomes.org/pub/release-37/plants/gff3/zea_mays/Zea_mays.AGPv4.37.gff3.gz.
#' Includes the 10 primary, Mt, and Pt chromosomes as well as unplaced scaffolds. Lists gene models and their start and end positions.
#' Contains some v3 ID's.
#'
#' @docType data
#' @usage data(maize.v4.37.chromosomal.gene.positions)
#' @keywords datasets
#'
#' @format A data frame with 4 columns and 39179 rows.
"maize.v4.37.chromosomal.gene.positions"

#' Map from genes to all available transcripts.
#'
#' Parsed from the zea mays b73 v4.37 gff3 file.  Excludes orphan exons. Excludes gene/transcripts with ID's beginning with MI, zma, or ENSRN, which
#' are all not standard v4 identifiers.
#'
#' @docType data
#' @usage data(gene.transcript.map)
#' @keywords datasets
#'
#' @format A data frame in long format.
"gene.transcript.map"
